#!/usr/bin/env python3
"""Generate PDF/HTML reports from Meta Ads analysis data."""

import argparse
import json
import os
import sys
from datetime import date, timedelta

PRIORITY_COLORS = {
    "critical": "#dc2626",
    "high": "#ea580c",
    "medium": "#ca8a04",
    "low": "#2563eb",
}


def generate_html(report_data):
    """Generate a self-contained HTML report from structured report data."""
    account_name = report_data.get("account_name", report_data.get("account_id", "Unknown"))
    date_range = report_data.get("date_range", "")
    sections = report_data.get("sections", [])

    sections_html = ""
    for section in sections:
        title = section.get("title", "")
        content = section.get("content", "")

        # Priority items
        items_html = ""
        for item in section.get("priority_items", []):
            level = item.get("level", "medium")
            color = PRIORITY_COLORS.get(level, "#6b7280")
            text = item.get("text", "")
            items_html += f'<div class="priority-item" style="border-left: 4px solid {color}; padding: 8px 12px; margin: 8px 0; background: #fafafa;"><strong style="color: {color}; text-transform: uppercase;">{level}</strong>: {text}</div>\n'

        # Metrics
        metrics_html = ""
        metrics = section.get("metrics", {})
        if metrics:
            metrics_html = '<div class="metrics-grid" style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 16px; margin: 16px 0;">\n'
            for key, value in metrics.items():
                formatted = f"${value:,.2f}" if key in ("spend", "cpa", "cost") else f"{value:,.1f}x" if key == "roas" else f"{value:,.0f}" if isinstance(value, (int, float)) else str(value)
                label = key.upper().replace("_", " ")
                metrics_html += f'<div class="metric-card" style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; text-align: center;"><div style="font-size: 24px; font-weight: bold; color: #1e293b;">{formatted}</div><div style="font-size: 12px; color: #64748b; margin-top: 4px;">{label}</div></div>\n'
            metrics_html += "</div>\n"

        sections_html += f"""
        <div class="section" style="margin: 32px 0;">
            <h2 style="color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">{title}</h2>
            <p style="color: #475569; line-height: 1.6;">{content}</p>
            {metrics_html}
            {items_html}
        </div>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meta Ads Report — {account_name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px 20px; color: #334155; }}
        .header {{ text-align: center; margin-bottom: 40px; }}
        .header h1 {{ color: #0f172a; margin-bottom: 4px; }}
        .header .subtitle {{ color: #64748b; font-size: 14px; }}
        @media print {{ body {{ padding: 20px; }} }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Meta Ads Analysis Report</h1>
        <div class="subtitle">{account_name} &mdash; {date_range}</div>
    </div>
    {sections_html}
    <footer style="text-align: center; color: #94a3b8; font-size: 12px; margin-top: 60px; padding-top: 20px; border-top: 1px solid #e2e8f0;">
        Generated by claude-meta-ads plugin
    </footer>
</body>
</html>"""
    return html


def generate_pdf(html_content, output_path):
    """Convert HTML to PDF using WeasyPrint."""
    from weasyprint import HTML
    HTML(string=html_content).write_pdf(output_path)


def write_file(path, content):
    """Write content to a file, creating directories if needed."""
    os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


def main():
    parser = argparse.ArgumentParser(description="Generate Meta Ads report")
    parser.add_argument("--input", required=True, help="Path to JSON report data file")
    parser.add_argument("--format", choices=["pdf", "html"], default="pdf", help="Output format")
    parser.add_argument("--output", help="Output file path (auto-generated if not set)")
    parser.add_argument("--json", action="store_true", default=True)

    args = parser.parse_args()

    with open(args.input, "r") as f:
        report_data = json.load(f)

    html = generate_html(report_data)

    account_id = report_data.get("account_id", "unknown")
    today = date.today().isoformat()

    if args.format == "html":
        output_path = args.output or f"meta-ads-report-{account_id}-{today}.html"
        write_file(output_path, html)
    else:
        output_path = args.output or f"meta-ads-report-{account_id}-{today}.pdf"
        generate_pdf(html, output_path)

    result = {"status": "ok", "format": args.format, "output_path": os.path.abspath(output_path)}
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
